### ISSUE TITLE
BUG: hard coded to use gpt-4o model

### ISSUE THREAD

**Issue by michaelneale** [square/goose#51]
Somehow it is always passing in gpt-4o/mini even when calling anthropic providers: 

eg in exchange: 

```python
    def complete(
        self,
        model: str,
        system: str,
        messages: List[Message],
        tools: List[Tool] = [],
        **kwargs: Dict[str, Any],
    ) -> Tuple[Message, Usage]:
        print("anthropic model", model)
```

Always shows a gpt4 model despite the config being: 

```yaml
anthropic:
  provider: anthropic
  processor: claude-3-5-sonnet-20240620
  accelerator: claude-3-5-sonnet-20240620
  moderator: truncate
  toolkits:
  - name: developer
    requires: {}
```

Seems a regression @baxen @lukealvoeiro with some refactoring with provider loading?

edit: this is due to truncate.py having it hard coded, fix: https://github.com/square/exchange/pull/35
